#!/bin/bash

set -e
set -u

root=$1
env_dir=$2
test_op=$3

test -e $env_dir || PYTHONPATH=$root guild init -y -P $root $env_dir

set +u

QUIET=1 source guild-env $env_dir

if [ "$NO_GPUS" == "1" ]; then
    RUN_OPTS='--no-gpus'
else
    RUN_OPTS=''
fi

guild run $RUN_OPTS -y $test_op
